### ISSUE TITLE
Not showing up on illumidesk

### ISSUE THREAD

**Issue by samlimish** [learn-co-curriculum/dsc-accessing-data-with-pandas#3]
I was able to open it up via using the github button, but when opened using the regular way, I got an error message saying that 'This page isn't working'

**Comment by hoffm386** [comment]
@samlimish I am not seeing any errors with opening this lesson in IllumiDesk at this time. It might have been a transient outage with the IllumiDesk platform. In general this is a good type of issue to raise with your teacher at the time when it's still happening so they can report it to IllumiDesk, rather than reporting on GitHub.

Going to close this out. Thanks!
